# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Taken and modified from https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa#:~:text=This%20is%20the%20only%20documented,coverage%20badges%20with%20GitHub%20Actions.&text=Go%20to%20github.com%2Fsettings,secret%20with%20the%20name%20GIST_SECRET%20.

name: Coverage

on:
  workflow_run:
    workflows: ['Unit Tests']
    types:
      - completed

jobs:
  cover:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get Coverage for badge
        run: |
        COVERAGE_STATEMENTS_TOTAL="$(jq '.total.statements.pct' c8-coverage/coverage-summary.json)"
        echo "COVERAGE=$(echo ${COVERAGE_STATEMENTS_TOTAL})" >> $GITHUB_ENV

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: fba0ebbf0edcc485926bb1b0905c3774
          filename: coverage.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest
